MCSE603P - Deep Learning Lab Slot : L3 + L4
Lab Ex1 (Part B) Introduction to TensorFlow

Name : Jagtap Mahesh Reg. 24MCS1017

1. Create two tensors of shape [2, 3] and perform element-wise addition and subtraction.


In [1]:
import tensorflow as tf

tensor_a = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor_b = tf.constant([[7, 8, 9], [10, 11, 12]])

addition = tf.add(tensor_a, tensor_b)
subtraction = tf.subtract(tensor_a, tensor_b)

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)


Addition:
 tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)
Subtraction:
 tf.Tensor(
[[-6 -6 -6]
 [-6 -6 -6]], shape=(2, 3), dtype=int32)


2. Reshape a tensor from shape [2, 3] to [3, 2].


In [2]:
reshaped_tensor = tf.reshape(tensor_a, [3, 2])
print("Reshaped Tensor:\n", reshaped_tensor)


Reshaped Tensor:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


3. Create a tensor with integers from 1 to 20 and extract values greater than 10.


In [3]:
tensor = tf.range(1, 21)
filtered_tensor = tf.boolean_mask(tensor, tensor > 10)
print("Filtered Tensor:\n", filtered_tensor)


Filtered Tensor:
 tf.Tensor([11 12 13 14 15 16 17 18 19 20], shape=(10,), dtype=int32)


4. Perform element-wise multiplication of two tensors of shape [3, 3].


In [4]:
tensor_x = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor_y = tf.constant([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

element_wise_multiplication = tf.multiply(tensor_x, tensor_y)
print("Element-wise Multiplication:\n", element_wise_multiplication)


Element-wise Multiplication:
 tf.Tensor(
[[ 9 16 21]
 [24 25 24]
 [21 16  9]], shape=(3, 3), dtype=int32)


5. Concatenate two tensors of shape [2, 3] along axis 0 and axis 1.


In [5]:
concat_axis_0 = tf.concat([tensor_a, tensor_b], axis=0)
concat_axis_1 = tf.concat([tensor_a, tensor_b], axis=1)

print("Concatenation along axis 0:\n", concat_axis_0)
print("Concatenation along axis 1:\n", concat_axis_1)


Concatenation along axis 0:
 tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
Concatenation along axis 1:
 tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


6. Create an identity matrix of size 4x4.


In [6]:
identity_matrix = tf.eye(4)
print("Identity Matrix:\n", identity_matrix)


Identity Matrix:
 tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


7. Calculate the mean and standard deviation of a tensor with random values of shape [10].


In [7]:
random_tensor = tf.random.uniform([10], minval=0, maxval=100)
mean = tf.reduce_mean(random_tensor)
stddev = tf.math.reduce_std(random_tensor)

print("Mean:", mean.numpy())
print("Standard Deviation:", stddev.numpy())


Mean: 51.835976
Standard Deviation: 30.582539


8. Create a tensor of shape [3, 4, 5] with random values and compute the sum along axis 1.


In [8]:
tensor_3d = tf.random.uniform([3, 4, 5])
sum_along_axis_1 = tf.reduce_sum(tensor_3d, axis=1)
print("Sum along axis 1:\n", sum_along_axis_1)


Sum along axis 1:
 tf.Tensor(
[[2.3687644 2.0519636 2.8991141 1.2970598 2.751189 ]
 [2.2071881 1.5771743 2.9412675 2.4192362 2.6229181]
 [1.175363  1.7601427 2.56619   1.0567586 3.1016   ]], shape=(3, 5), dtype=float32)


9. Use tf.argmax to find the index of the maximum value in a 2D tensor.


In [9]:
tensor_2d = tf.constant([[1, 5, 3], [4, 2, 8]])
max_index = tf.argmax(tensor_2d, axis=1)
print("Index of maximum values:\n", max_index)


Index of maximum values:
 tf.Tensor([1 2], shape=(2,), dtype=int64)


10. Perform a batch matrix multiplication on two tensors of shape [2, 3, 3].


In [10]:
tensor_batch_1 = tf.random.uniform([2, 3, 3])
tensor_batch_2 = tf.random.uniform([2, 3, 3])

batch_multiplication = tf.matmul(tensor_batch_1, tensor_batch_2)
print("Batch Matrix Multiplication:\n", batch_multiplication)


Batch Matrix Multiplication:
 tf.Tensor(
[[[1.2220974  1.1484401  0.76519823]
  [1.8236518  1.8155338  1.1037693 ]
  [1.2433233  1.2376136  0.7082404 ]]

 [[1.0278755  0.36493906 0.2954483 ]
  [1.3113047  0.6134627  1.1268651 ]
  [1.1242282  0.59886247 0.87061906]]], shape=(2, 3, 3), dtype=float32)
