# MCSE603P - Deep Learning Lab        Slot : L3 + L4

---
Lab Ex1 (Part A) Introduction to TensorFlow

Name : Jagtap Mahesh
Reg. 24MCS1017

1.Create a vector, scalar, matrix and tensor with values of your choice
using tf.constant().

In [ ]:
import tensorflow as tf

# Create a scalar
scalar = tf.constant(10)

# Create a vector
vector = tf.constant([1, 2, 3, 4, 5])

# Create a matrix
matrix = tf.constant([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Create a tensor
tensor = tf.constant([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("Tensor:\n", tensor)

Scalar: tf.Tensor(10, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Matrix:
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
Tensor:
 tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


2.Find the shape, rank and size of the tensors (which you created for Q1)

In [ ]:


print("Scalar Shape:", scalar.shape)
print("Scalar Rank:", scalar.ndim)
print("Scalar Size:", tf.size(scalar))

print("Vector Shape:", vector.shape)
print("Vector Rank:", vector.ndim)
print("Vector Size:", tf.size(vector))

print("Matrix Shape:", matrix.shape)
print("Matrix Rank:", matrix.ndim)
print("Matrix Size:", tf.size(matrix))

print("Tensor Shape:", tensor.shape)
print("Tensor Rank:", tensor.ndim)
print("Tensor Size:", tf.size(tensor))

Scalar Shape: ()
Scalar Rank: 0
Scalar Size: tf.Tensor(1, shape=(), dtype=int32)
Vector Shape: (5,)
Vector Rank: 1
Vector Size: tf.Tensor(5, shape=(), dtype=int32)
Matrix Shape: (3, 3)
Matrix Rank: 2
Matrix Size: tf.Tensor(9, shape=(), dtype=int32)
Tensor Shape: (2, 2, 3)
Tensor Rank: 3
Tensor Size: tf.Tensor(12, shape=(), dtype=int32)


3.Create two tensors containing random values between 0 and 1 with shape [5, 300]

> Add blockquote



In [ ]:
tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)
tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)

Tensor 1:
 tf.Tensor(
[[0.05306041 0.43060517 0.25086045 ... 0.26206815 0.41978693 0.53619325]
 [0.82701087 0.2599851  0.3166361  ... 0.41629505 0.00677907 0.77845347]
 [0.2345612  0.48288262 0.33332086 ... 0.07978559 0.21163666 0.9030403 ]
 [0.06230009 0.05912578 0.9520235  ... 0.71555495 0.0184319  0.05913734]
 [0.30858958 0.97301114 0.14844155 ... 0.10970187 0.08043885 0.5919429 ]], shape=(5, 300), dtype=float32)
Tensor 2:
 tf.Tensor(
[[0.98714256 0.6184623  0.6511196  ... 0.32264328 0.3044951  0.7013577 ]
 [0.10376239 0.52484906 0.8959751  ... 0.6911777  0.57439625 0.68267   ]
 [0.8680341  0.69719744 0.4296422  ... 0.52198017 0.9007896  0.50477254]
 [0.04957807 0.1105274  0.3682084  ... 0.9854803  0.43290508 0.2915765 ]
 [0.15719962 0.23663509 0.31696284 ... 0.38301456 0.19726026 0.29655135]], shape=(5, 300), dtype=float32)


4.Multiply the two tensors (which you created for Question 3) using matrix
multiplication.

In [ ]:
# Matrix multiplication requires compatible shapes.
# Transpose tensor2 to make shapes compatible for multiplication.
# Shape of tensor1: [5, 300]
# Shape of tensor2 (transposed): [300, 5]

tensor2_transposed = tf.transpose(tensor2)
multiplied_tensor = tf.matmul(tensor1, tensor2_transposed)

print("Multiplied Tensor:\n", multiplied_tensor)

Multiplied Tensor:
 tf.Tensor(
[[76.44772  71.711075 75.08182  74.78281  72.84058 ]
 [76.009735 76.931816 76.19641  76.07572  74.15805 ]
 [72.60649  75.079605 74.11636  74.94653  69.87314 ]
 [79.026794 76.950836 79.7824   77.86337  75.29499 ]
 [79.131256 76.9599   78.8629   75.77054  74.21129 ]], shape=(5, 5), dtype=float32)


5.Multiply the two tensors (which you created for Question 3) using dot product.

In [ ]:
dot_product = tf.tensordot(tensor1, tf.transpose(tensor2), axes=1)

print("Dot Product of Tensors:\n", dot_product)

Dot Product of Tensors:
 tf.Tensor(
[[76.44772  71.711075 75.08182  74.78281  72.84058 ]
 [76.009735 76.931816 76.19641  76.07572  74.15805 ]
 [72.60649  75.079605 74.11636  74.94653  69.87314 ]
 [79.026794 76.950836 79.7824   77.86337  75.29499 ]
 [79.131256 76.9599   78.8629   75.77054  74.21129 ]], shape=(5, 5), dtype=float32)


6.Create a tensor with random values between 0 and 1 with shape [224, 224,
3].

In [ ]:
random_tensor = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)

print(random_tensor)

tf.Tensor(
[[[0.2421763  0.82935536 0.32439578]
  [0.31803036 0.05338144 0.11010206]
  [0.5878365  0.2911867  0.57394207]
  ...
  [0.7581792  0.16657114 0.6825017 ]
  [0.3930726  0.06793702 0.68028414]
  [0.13317633 0.8662126  0.8819821 ]]

 [[0.15374339 0.53278506 0.9604813 ]
  [0.00262535 0.81609297 0.13858294]
  [0.14251971 0.6003659  0.9859736 ]
  ...
  [0.89181435 0.9640503  0.715289  ]
  [0.7355523  0.06189764 0.38455737]
  [0.24059093 0.33377242 0.8560542 ]]

 [[0.4190961  0.35560155 0.78004587]
  [0.17830741 0.1855073  0.11715949]
  [0.76018405 0.7245709  0.15386677]
  ...
  [0.1396153  0.46305275 0.83198714]
  [0.5232308  0.919541   0.19292903]
  [0.7540504  0.16013718 0.47429526]]

 ...

 [[0.17210078 0.17536724 0.36468792]
  [0.77472687 0.1993041  0.9384799 ]
  [0.96457696 0.67908144 0.48629093]
  ...
  [0.7930995  0.7650589  0.5882399 ]
  [0.5962484  0.4459145  0.7116078 ]
  [0.16882706 0.9032532  0.01493227]]

 [[0.36864007 0.4254713  0.9485451 ]
  [0.37164438 0.5782703  0

7. Find the min and max values of the tensor (which you created for Question 6)

In [ ]:
min_value = tf.reduce_min(random_tensor)
max_value = tf.reduce_max(random_tensor)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: tf.Tensor(8.702278e-06, shape=(), dtype=float32)
Maximum value: tf.Tensor(0.99999094, shape=(), dtype=float32)


8.Create a tensor with random values of shape [1, 224, 224, 3] then
squeeze it to change the shape to [224, 224, 3].


In [ ]:
import tensorflow as tf

random_tensor2 = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=100)

squeezed_tensor = tf.squeeze(random_tensor2)

print("Original shape:", random_tensor2.shape)
print("Squeezed shape:", squeezed_tensor.shape)

Original shape: (1, 224, 224, 3)
Squeezed shape: (224, 224, 3)


9.Create a tensor with shape [10] using your own choice of values, then find
the index which has the maximum value.

In [ ]:
tensor3 = tf.constant([5, 2, 8, 1, 9, 4, 7, 3, 6, 0])

max_index = tf.argmax(tensor3)

print("Tensor:", tensor3)
print("Index of maximum value:", max_index)

Tensor: tf.Tensor([5 2 8 1 9 4 7 3 6 0], shape=(10,), dtype=int32)
Index of maximum value: tf.Tensor(4, shape=(), dtype=int64)


10.One-hot encode the tensor you created in 9

In [ ]:
# Define the depth for one-hot encoding (maximum value + 1)
depth = tf.reduce_max(tensor3).numpy() + 1
one_hot_tensor = tf.one_hot(tensor3, depth)

print("Original tensor:", tensor3)
print("One-hot encoded tensor:\n", one_hot_tensor)

Original tensor: tf.Tensor([5 2 8 1 9 4 7 3 6 0], shape=(10,), dtype=int32)
One-hot encoded tensor:
 tf.Tensor(
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
